name: "Terraform S3 Backend Action"
author: "Amann Malik"
description: "Connect to any Terraform S3 backend state authorized to your repository via an IAM OIDC role."
branding:
  icon: "download-cloud"
  color: "purple"
inputs:
  account-id:
    description: "AWS account ID of the Terraform state S3 bucket"
    required: true
  role:
    description: "Name of the IAM OIDC role assumable by the GitHub repository"
    required: true
  region:
    description: "AWS region of the Terraform state S3 bucket"
    required: true
  bucket:
    description: "S3 bucket of the Terraform state"
    required: true
  key:
    description: "S3 key of the Terraform state"
    required: false
    default: "terraform.tfstate"
outputs:
  path:
    description: "Path to the backend config file for use with Terraform init"
runs:
  using: "node12"
  main: "dist/index.js"
